export const brand = {
  name: 'goonjaa',
  ownerName: 'Srijita Roy',
  ownerDisplayName: 'Srijita',
  siteUrl: 'https://goonjaa.vercel.app',
  description: 'Handcrafted terracotta jewellery shaped and painted by a woman-led studio in India.',
  instagramHandle: '@goonjaa.srijita',
  instagramUrl: 'https://instagram.com/goonjaa.srijita',
  facebookUrl: 'https://www.facebook.com/profile.php?id=61554180150901',
  youtubeUrl: 'https://www.youtube.com/@goonjaa.srijita',
  email: 'goonjaa.srijita@gmail.com',
  ownerEmail: 'goonjaa.srijita@gmail.com',
  phone: '+91 86974 52473',
  whatsappPhone: '+918697452473',
  ownerPhoto: '/images/founder_studio.png',
  ownerPhotoAlt: 'Srijita Roy, the goonjaa artist, working in her home studio',
  studioPhoto: '/images/hero_clay_sculpting.svg',
  studioPhotoAlt: 'The goonjaa studio where terracotta jewellery is shaped and painted by hand',
} as const;
