export const brand = {
  name: 'goonjaa',
  siteUrl: 'https://goonjaa.in',
  description: 'Handcrafted terracotta jewellery shaped and painted by a woman-led studio in India.',
  instagramHandle: '@goonjaa.srijita',
  instagramUrl: 'https://instagram.com/goonjaa.srijita',
  facebookUrl: '',
  youtubeUrl: '',
  email: 'hello@goonjaa.in',
  ownerEmail: 'hello@goonjaa.in',
  phone: '+91 89102 14167',
  whatsappPhone: '+918910214167',
  ownerPhoto: '/images/founder_studio.png',
  ownerPhotoAlt: 'The goonjaa artist working in her home studio',
  studioPhoto: '/images/founder_studio.png',
  studioPhotoAlt: 'The goonjaa studio where terracotta jewellery is shaped and painted by hand',
} as const;
